### ISSUE TITLE
Fibers is missing in tests

### ISSUE THREAD

**Issue by schlamar** [saghul/evergreen#12]

**Comment by schlamar** [comment]
Ah sorry, it should be bundled. However, it get the following issue while running tests:

```
======================================================================
ERROR: Failure: ImportError (cannot import name six)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\nose\loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "c:\Python27\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "c:\Python27\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "c:\Users\schlaich\Documents\GitHub\evergreen\tests\test_timeout.py", line 2, in <module>
    from common import unittest, EvergreenTestCase
  File "c:\Users\schlaich\Documents\GitHub\evergreen\tests\common.py", line 13, in <module>
    import evergreen
  File "../evergreen\__init__.py", line 8, in <module>
    from evergreen.tasks import *
  File "../evergreen\tasks.py", line 7, in <module>
    from evergreen import six
ImportError: cannot import name six
```

**Comment by schlamar** [comment]
However, this works:

```
$ python
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import evergreen
>>> from evergreen import six
>>>
```

**Comment by schlamar** [comment]
Ah sorry, this is an import regression error, first one is:

```
======================================================================
ERROR: Failure: ImportError (No module named fibers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\nose\loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "c:\Python27\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "c:\Python27\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "c:\Users\schlaich\Documents\GitHub\evergreen\tests\test_channel.py", line 2, in <module>
    from common import unittest, EvergreenTestCase
  File "c:\Users\schlaich\Documents\GitHub\evergreen\tests\common.py", line 13, in <module>
    import evergreen
  File "../evergreen\__init__.py", line 8, in <module>
    from evergreen.tasks import *
  File "../evergreen\tasks.py", line 10, in <module>
    from fibers import Fiber
ImportError: No module named fibers
```

**Comment by schlamar** [comment]
I'm using a virtualenv, btw.

**Comment by schlamar** [comment]
Mhh, I guess this was a setup issue. I upgraded virtualenv and re-created the env, now the tests work.
