### ISSUE TITLE
Failing UDP test on Windows

### ISSUE THREAD

**Issue by schlamar** [saghul/evergreen#13]
```
test_udp_ping_pong (test_io.IOTests) ... Traceback (most recent call last):
  File "../evergreen\core\loop.py", line 372, in _process_ready
    handler._run()
  File "../evergreen\core\loop.py", line 47, in _run
    self._callback(*self._args, **self._kwargs)
  File "../evergreen\locks.py", line 58, in _notify_waiters
    waiter.switch()
  File "../evergreen\tasks.py", line 135, in __run
    self.run()
  File "../evergreen\tasks.py", line 87, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\schlaich\Documents\GitHub\evergreen\tests\test_io.py", line 178, in connect
    client.send(b'PING', TEST_SERVER)
  File "../evergreen\io\udp.py", line 42, in send
    f.get()
  File "../evergreen\futures\_base.py", line 341, in get
    return self._get_result()
  File "../evergreen\futures\_base.py", line 356, in _get_result
    raise self._exception
UDPError: (6, 'address not available')
```

**Comment by saghul** [comment]
I fixed this case in https://github.com/saghul/evergreen/commit/2a7f5b8e8ed12a6a50b1d4bd77ba11e5ab066591, now all tests pass on Windows 7 me. Can you check it out as well?

Thanks!

**Comment by schlamar** [comment]
```
$ nosetests
...............S..............................SSSS.........................
----------------------------------------------------------------------
Ran 75 tests in 1.495s

OK (SKIP=5)
```

:+1:

**Comment by saghul** [comment]
Awesome, thanks for testing!
