### ISSUE TITLE
evergreen.EventLoop() lauches exception

### ISSUE THREAD

**Issue by francois-vincent** [saghul/evergreen#16]
Hi saghul,

I've just installed evergreen to have a look and perform basic tests:

> cat /etc/issue
> 
> >  Ubuntu 14.04.1 LTS
> 
> pip install evergreen
> 
> >  Downloading evergreen-0.1.0.tar.gz
> >  Downloading fibers-0.4.0.tar.gz
> >  Downloading pyuv-1.0.1.tar.gz

but I've been stopped at first step:

> python
> 
> > import evergreen
> > loop=evergreen.EventLoop()
> > 
> > > Traceback (most recent call last):
> > >  File "<console>", line 1, in <module>
> > >  File "/home/francois/.local/share/virtualenvs/py2/local/lib/python2.7/site-packages/evergreen/core/loop.py", line 126, in **init**
> > >    self._ready_processor.unref()
> > > AttributeError: 'pyuv.Check' object has no attribute 'unref'

I thought probably an evergreen/pyuv version mismatch :)
But now that I checked, there seems to be a single version of pyuv available on pypi:

> pip install yolk
> yolk -V pyuv
> 
> > pyuv 1.0.1

If you can have a look ?

François

**Comment by saghul** [comment]
You're right, I have not updated evergreen to match the API changes in pyuv due to lack of time :-S I'll fix it as soon as I can, but if you feel like going for it, don't hesitate to send a PR :-)
