### ISSUE TITLE
'pyuv._cpyuv.Check' object has no attribute 'unref'

### ISSUE THREAD

**Issue by liuliqiang** [saghul/evergreen#17]
when i using evergreen == 0.1.0 , i install it with pip

`pip install evergreen`
and it install pyuv == 1.3.0, and it try this example:

```
#!/usr/bin/env python
# encoding: utf-8
import evergreen

# Create the global loop
loop = evergreen.EventLoop()

# Start the loop
loop.run()
```

it get following error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    loop = evergreen.EventLoop()
  File "/home/yetship/.virtualenvs/evergreen/lib/python2.7/site-packages/evergreen/core/loop.py", line 126, in __init__
    self._ready_processor.unref()
AttributeError: 'pyuv._cpyuv.Check' object has no attribute 'unref'
```

**Comment by saghul** [comment]
Good catch, I need to update the syntax to the new pyuv API, will do that as soon as I get some time.

**Comment by liuliqiang** [comment]
sounds good, anything i can help?

**Comment by saghul** [comment]
If you feel like it, then great!  Basically check for the API changes in pyuv and adjust accordingly.  ref / unref functions are gone, is now a property, for example.

There is not much to adjust IIRC.

**Comment by liuliqiang** [comment]
it seems good, however i'm not farmiliar with pyuv, i just try evergreen for learning cooperative multitasking and i/o. i'm sorry for that, and maybe what i can do is waitting for the good news.
