### ISSUE TITLE
Dead-locking test cases on Windows

### ISSUE THREAD

**Issue by schlamar** [saghul/evergreen#6]
There are multiple test cases dead-locking on Windows:
- test_future_wait_multiple_wait_first (test_futures.FuturesTests)
- test_stop2 (test_loop.LoopTests)
- test_task_join_timeout (test_tasks.TasksTests)
- test_timeout (test_timeout.TimeoutTests)

Any idea?

**Comment by saghul** [comment]
I have yet to test it on Windows, will do that for the next release.

**Comment by saghul** [comment]
Some of the new tests for io module are also failing:
- test_pipe_read_error
- test_tcp_read

**Comment by saghul** [comment]
These failures:
- test_stop2 (test_loop.LoopTests)
- test_task_join_timeout (test_tasks.TasksTests)
- test_timeout (test_timeout.TimeoutTests)

Are a result of this issue: https://github.com/joyent/libuv/issues/796

**Comment by schlamar** [comment]
Ah, nice. Tests are running now. But I get a traceback (without making the test fail):

```
test_tcp_read_error (test_io.IOTests) ... Traceback (most recent call last):
  File "C:\Users\schlaich\Documents\GitHub\evergreen\evergreen\loop.py", line 383, in _process_ready
    handler()
  File "C:\Users\schlaich\Documents\GitHub\evergreen\evergreen\loop.py", line 63, in __call__
    self._callback(*self._args, **self._kwargs)
  File "C:\Users\schlaich\Documents\GitHub\evergreen\evergreen\tasks.py", line 135, in switch
    return super(Task, self).switch(*args, **kwargs)
  File "C:\Users\schlaich\Documents\GitHub\evergreen\evergreen\tasks.py", line 145, in run
    self.run_()
  File "C:\Users\schlaich\Documents\GitHub\evergreen\evergreen\tasks.py", line 82, in run_
    self._target(*self._args, **self._kwargs)
  File "C:\Users\schlaich\Documents\GitHub\evergreen\tests\test_io.py", line 26, in handle_connection
    data = connection.read_until('\n')
  File "C:\Users\schlaich\Documents\GitHub\evergreen\evergreen\io\stream.py", line 38, in read_until
    return self._do_read(delimiter=delimiter)
  File "C:\Users\schlaich\Documents\GitHub\evergreen\evergreen\io\stream.py", line 75, in _do_read
    self._check_closed()
  File "C:\Users\schlaich\Documents\GitHub\evergreen\evergreen\io\stream.py", line 93, in _check_closed
    raise self.error_class('stream is closed')
TCPError: stream is closed
ok
```

**Comment by saghul** [comment]
Can you try to apply this fix also for tcp_read_error test case? https://github.com/saghul/evergreen/commit/a38333cd213f559cb121c5a4c8085ff6e39ccdcd

**Comment by schlamar** [comment]
> Can you try to apply this fix also for tcp_read_error test case?

Yes, that helps...

**Comment by saghul** [comment]
Thanks for testing, I pushed the fix.

**Comment by saghul** [comment]
Alright, this issue is "solved", however I'll keep it open until I remove the nasty workaround added in b509894

**Comment by schlamar** [comment]
`evergreen.sleep(0)` is fine, too (but not in the pipe test).

**Comment by saghul** [comment]
Yeah, we basically need to switch the task to allow the listen callback to be run, which seems to take a bit longer on Windows, I set it to the same value so that I don't wonder why I set them different, 6 months from now ;-)

**Comment by saghul** [comment]
Could you please test this branch? https://github.com/saghul/evergreen/tree/idle_processor It simplifies the logic a bit and should also fix this issue on Windows, without doing nasty workarounds.

**Comment by schlamar** [comment]
```
test_udp_ping_pong (test_io.IOTests) ... Traceback (most recent call last):
  File "../evergreen\core\loop.py", line 372, in _process_ready
    handler._run()
  File "../evergreen\core\loop.py", line 47, in _run
    self._callback(*self._args, **self._kwargs)
  File "../evergreen\locks.py", line 58, in _notify_waiters
    waiter.switch()
  File "../evergreen\tasks.py", line 135, in __run
    self.run()
  File "../evergreen\tasks.py", line 87, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\schlaich\Documents\GitHub\evergreen\tests\test_io.py", line 178, in connect
    client.send(b'PING', TEST_SERVER)
  File "../evergreen\io\udp.py", line 42, in send
    f.get()
  File "../evergreen\futures\_base.py", line 341, in get
    return self._get_result()
  File "../evergreen\futures\_base.py", line 356, in _get_result
    raise self._exception
UDPError: (6, 'address not available')
```

**Comment by saghul** [comment]
Thanks for running it. Do these tests fail? https://github.com/saghul/evergreen/issues/6#issuecomment-17473654

I'll setup my dev env again somewhere this week and iron out this bugs before making a new release.

**Comment by schlamar** [comment]
> Do these tests fail? #6

They are fine.

**Comment by saghul** [comment]
Thanks for confirming!

**Comment by schlamar** [comment]
#13
